services:
  api:
    container_name: ...-rest-api
    build: .
    ports:
      - "4001:4000"
    env_file:
      - .env.production.local
    depends_on:
      - db
    networks:
      - ...
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    container_name: ...-database
    image: postgres:17
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ..._db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ...

volumes:
  db-data:

networks:
  ...:
